name: Run Tests

on:
  push:
    branches: [ master ]

jobs:
  check-test-scripts:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Check for test scripts
      run: |
        if [ ! -f "tests.sh" ]; then
          echo "Napaka: Testna skripta ne obstajajo." > napaka.txt
        else
          touch napaka.txt  # Ustvari prazno datoteko, če ni napake
        fi

    - name: Upload error file
      uses: actions/upload-artifact@v3
      with:
        name: error-artifact
        path: napaka.txt

  run-tests:
    needs: check-test-scripts
    runs-on: self-hosted
    strategy:
      matrix:
        test_type: [basic, edge, stress]
    steps:
    - uses: actions/checkout@v3

    - name: Download error artifact
      uses: actions/download-artifact@v3
      with:
        name: error-artifact

    - name: Check for errors
      run: |
        if [ -s napaka.txt ]; then
          echo "Prekinjam zaradi napake v prvem poslu:"
          cat napaka.txt
          exit 1
        fi

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++

    - name: Compile and run tests (${{ matrix.test_type }})
      run: |
        g++ -o radix_sort radix_sort.cpp
        ./tests.sh ${{ matrix.test_type }}